server:
  port: 7011
spring:
  #main:
    #banner-mode: OFF
  application:
    name: spring-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/wengith/spring-cloud-config.git
          #uri: file:///D:\TestGit\TestGit\spring-cloud-config
          username: wengith
          password: wengit123
          search-paths: '{application}'
    bus:
      refresh:
        enabled: true
  #security:
   # user:
      #name: wen
      #password: security

#eureka info
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/

management:
  endpoints:
    web:
      exposure:
        include: '*'