spring: 
  redis:    #redis 配置（默认本地单节点，可变更为Redis集群）
    database: 0  
    password:  
    host: localhost
    port: 6379 
#    cluster:
#      nodes:
#        - 10.10.68.43:6379
#        - 10.10.68.145:6379
#        - 10.10.68.146:6379
#        - 10.10.68.43:6380
#        - 10.10.68.145:6380
#        - 10.10.68.146:6380 
#      max-redirects: 5
    jedis:
      pool:
        max-wait: 30 
        max-idle: 5  
  cache:
    type: redis  
  application:
    name: mono-robot-server    
  jackson:
    date-format: yyyy-MM-dd HH:mm.ss
  messages:
    basename: i18n/defalultMessages,i18n/messages #指定message的basename，多个以逗号分隔，如果不加包名的话，默认从classpath路径开始，默认: messages
    encoding: UTF-8 #设定Message bundles的编码，默认: UTF-8    
  datasource: #数据源配置
    url: jdbc:mysql://localhost:3306/platform_devdb?useUnicode=true&amp;characterEncoding=utf-8
    username: root
    password: admin
    hikari:      
      minimum-idle: 5 #最小空闲连接数，默认和maximum-pool-size值一样(性能测试和生产环境时不要设置，保持固定连接池)
      maximum-pool-size: 150 # 连接池中可同时连接的最大连接数, 当池中没有空闲连接可用时,就会阻塞直到超出connectionTimeout设定的数值
  profiles:
    active: dev
server:
  port: 15020
  
mybatis: #MyBatis配置
  mapperLocations: classpath*:mapper/**/*Dao.xml
  executor-type: REUSE     