server:
  port: 7016
spring:
  application:
    name: gateway-server

  cloud:
    gateway:
      routes:
        - id: test_route
          uri: http://www.baidu.com
          predicates:
            - Path=/test
          filters:
            - StripPrefix=1


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/